// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: packet.proto

package mydpi;

public final class Packet {
  private Packet() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface packetOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mydpi.packet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string ipPorto2Name = 1;</code>
     */
    java.lang.String getIpPorto2Name();
    /**
     * <code>string ipPorto2Name = 1;</code>
     */
    com.google.protobuf.ByteString
        getIpPorto2NameBytes();

    /**
     * <code>string srcIp = 2;</code>
     */
    java.lang.String getSrcIp();
    /**
     * <code>string srcIp = 2;</code>
     */
    com.google.protobuf.ByteString
        getSrcIpBytes();

    /**
     * <code>uint32 srcPort = 3;</code>
     */
    int getSrcPort();

    /**
     * <code>string dstIp = 4;</code>
     */
    java.lang.String getDstIp();
    /**
     * <code>string dstIp = 4;</code>
     */
    com.google.protobuf.ByteString
        getDstIpBytes();

    /**
     * <code>uint32 dstPort = 5;</code>
     */
    int getDstPort();

    /**
     * <code>string proto = 6;</code>
     */
    java.lang.String getProto();
    /**
     * <code>string proto = 6;</code>
     */
    com.google.protobuf.ByteString
        getProtoBytes();

    /**
     * <code>uint32 srcPktNums = 7;</code>
     */
    int getSrcPktNums();

    /**
     * <code>uint32 srcBytes = 8;</code>
     */
    int getSrcBytes();

    /**
     * <code>uint32 dstPktNums = 9;</code>
     */
    int getDstPktNums();

    /**
     * <code>uint32 dstBytes = 10;</code>
     */
    int getDstBytes();

    /**
     * <code>uint32 vlan = 11;</code>
     */
    int getVlan();

    /**
     * <code>string host = 12;</code>
     */
    java.lang.String getHost();
    /**
     * <code>string host = 12;</code>
     */
    com.google.protobuf.ByteString
        getHostBytes();

    /**
     * <code>string client = 13;</code>
     */
    java.lang.String getClient();
    /**
     * <code>string client = 13;</code>
     */
    com.google.protobuf.ByteString
        getClientBytes();

    /**
     * <code>string server = 14;</code>
     */
    java.lang.String getServer();
    /**
     * <code>string server = 14;</code>
     */
    com.google.protobuf.ByteString
        getServerBytes();

    /**
     * <code>string btHash = 15;</code>
     */
    java.lang.String getBtHash();
    /**
     * <code>string btHash = 15;</code>
     */
    com.google.protobuf.ByteString
        getBtHashBytes();

    /**
     * <code>string info = 16;</code>
     */
    java.lang.String getInfo();
    /**
     * <code>string info = 16;</code>
     */
    com.google.protobuf.ByteString
        getInfoBytes();

    /**
     * <code>int32 timestamp = 17;</code>
     */
    int getTimestamp();
  }
  /**
   * Protobuf type {@code mydpi.packet}
   */
  public  static final class packet extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mydpi.packet)
      packetOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use packet.newBuilder() to construct.
    private packet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private packet() {
      ipPorto2Name_ = "";
      srcIp_ = "";
      srcPort_ = 0;
      dstIp_ = "";
      dstPort_ = 0;
      proto_ = "";
      srcPktNums_ = 0;
      srcBytes_ = 0;
      dstPktNums_ = 0;
      dstBytes_ = 0;
      vlan_ = 0;
      host_ = "";
      client_ = "";
      server_ = "";
      btHash_ = "";
      info_ = "";
      timestamp_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private packet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              ipPorto2Name_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              srcIp_ = s;
              break;
            }
            case 24: {

              srcPort_ = input.readUInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              dstIp_ = s;
              break;
            }
            case 40: {

              dstPort_ = input.readUInt32();
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              proto_ = s;
              break;
            }
            case 56: {

              srcPktNums_ = input.readUInt32();
              break;
            }
            case 64: {

              srcBytes_ = input.readUInt32();
              break;
            }
            case 72: {

              dstPktNums_ = input.readUInt32();
              break;
            }
            case 80: {

              dstBytes_ = input.readUInt32();
              break;
            }
            case 88: {

              vlan_ = input.readUInt32();
              break;
            }
            case 98: {
              java.lang.String s = input.readStringRequireUtf8();

              host_ = s;
              break;
            }
            case 106: {
              java.lang.String s = input.readStringRequireUtf8();

              client_ = s;
              break;
            }
            case 114: {
              java.lang.String s = input.readStringRequireUtf8();

              server_ = s;
              break;
            }
            case 122: {
              java.lang.String s = input.readStringRequireUtf8();

              btHash_ = s;
              break;
            }
            case 130: {
              java.lang.String s = input.readStringRequireUtf8();

              info_ = s;
              break;
            }
            case 136: {

              timestamp_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mydpi.Packet.internal_static_mydpi_packet_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mydpi.Packet.internal_static_mydpi_packet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mydpi.Packet.packet.class, mydpi.Packet.packet.Builder.class);
    }

    public static final int IPPORTO2NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object ipPorto2Name_;
    /**
     * <code>string ipPorto2Name = 1;</code>
     */
    public java.lang.String getIpPorto2Name() {
      java.lang.Object ref = ipPorto2Name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ipPorto2Name_ = s;
        return s;
      }
    }
    /**
     * <code>string ipPorto2Name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIpPorto2NameBytes() {
      java.lang.Object ref = ipPorto2Name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ipPorto2Name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SRCIP_FIELD_NUMBER = 2;
    private volatile java.lang.Object srcIp_;
    /**
     * <code>string srcIp = 2;</code>
     */
    public java.lang.String getSrcIp() {
      java.lang.Object ref = srcIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        srcIp_ = s;
        return s;
      }
    }
    /**
     * <code>string srcIp = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSrcIpBytes() {
      java.lang.Object ref = srcIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        srcIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SRCPORT_FIELD_NUMBER = 3;
    private int srcPort_;
    /**
     * <code>uint32 srcPort = 3;</code>
     */
    public int getSrcPort() {
      return srcPort_;
    }

    public static final int DSTIP_FIELD_NUMBER = 4;
    private volatile java.lang.Object dstIp_;
    /**
     * <code>string dstIp = 4;</code>
     */
    public java.lang.String getDstIp() {
      java.lang.Object ref = dstIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dstIp_ = s;
        return s;
      }
    }
    /**
     * <code>string dstIp = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDstIpBytes() {
      java.lang.Object ref = dstIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dstIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DSTPORT_FIELD_NUMBER = 5;
    private int dstPort_;
    /**
     * <code>uint32 dstPort = 5;</code>
     */
    public int getDstPort() {
      return dstPort_;
    }

    public static final int PROTO_FIELD_NUMBER = 6;
    private volatile java.lang.Object proto_;
    /**
     * <code>string proto = 6;</code>
     */
    public java.lang.String getProto() {
      java.lang.Object ref = proto_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        proto_ = s;
        return s;
      }
    }
    /**
     * <code>string proto = 6;</code>
     */
    public com.google.protobuf.ByteString
        getProtoBytes() {
      java.lang.Object ref = proto_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        proto_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SRCPKTNUMS_FIELD_NUMBER = 7;
    private int srcPktNums_;
    /**
     * <code>uint32 srcPktNums = 7;</code>
     */
    public int getSrcPktNums() {
      return srcPktNums_;
    }

    public static final int SRCBYTES_FIELD_NUMBER = 8;
    private int srcBytes_;
    /**
     * <code>uint32 srcBytes = 8;</code>
     */
    public int getSrcBytes() {
      return srcBytes_;
    }

    public static final int DSTPKTNUMS_FIELD_NUMBER = 9;
    private int dstPktNums_;
    /**
     * <code>uint32 dstPktNums = 9;</code>
     */
    public int getDstPktNums() {
      return dstPktNums_;
    }

    public static final int DSTBYTES_FIELD_NUMBER = 10;
    private int dstBytes_;
    /**
     * <code>uint32 dstBytes = 10;</code>
     */
    public int getDstBytes() {
      return dstBytes_;
    }

    public static final int VLAN_FIELD_NUMBER = 11;
    private int vlan_;
    /**
     * <code>uint32 vlan = 11;</code>
     */
    public int getVlan() {
      return vlan_;
    }

    public static final int HOST_FIELD_NUMBER = 12;
    private volatile java.lang.Object host_;
    /**
     * <code>string host = 12;</code>
     */
    public java.lang.String getHost() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        host_ = s;
        return s;
      }
    }
    /**
     * <code>string host = 12;</code>
     */
    public com.google.protobuf.ByteString
        getHostBytes() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        host_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLIENT_FIELD_NUMBER = 13;
    private volatile java.lang.Object client_;
    /**
     * <code>string client = 13;</code>
     */
    public java.lang.String getClient() {
      java.lang.Object ref = client_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        client_ = s;
        return s;
      }
    }
    /**
     * <code>string client = 13;</code>
     */
    public com.google.protobuf.ByteString
        getClientBytes() {
      java.lang.Object ref = client_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        client_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVER_FIELD_NUMBER = 14;
    private volatile java.lang.Object server_;
    /**
     * <code>string server = 14;</code>
     */
    public java.lang.String getServer() {
      java.lang.Object ref = server_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        server_ = s;
        return s;
      }
    }
    /**
     * <code>string server = 14;</code>
     */
    public com.google.protobuf.ByteString
        getServerBytes() {
      java.lang.Object ref = server_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        server_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BTHASH_FIELD_NUMBER = 15;
    private volatile java.lang.Object btHash_;
    /**
     * <code>string btHash = 15;</code>
     */
    public java.lang.String getBtHash() {
      java.lang.Object ref = btHash_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        btHash_ = s;
        return s;
      }
    }
    /**
     * <code>string btHash = 15;</code>
     */
    public com.google.protobuf.ByteString
        getBtHashBytes() {
      java.lang.Object ref = btHash_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        btHash_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int INFO_FIELD_NUMBER = 16;
    private volatile java.lang.Object info_;
    /**
     * <code>string info = 16;</code>
     */
    public java.lang.String getInfo() {
      java.lang.Object ref = info_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        info_ = s;
        return s;
      }
    }
    /**
     * <code>string info = 16;</code>
     */
    public com.google.protobuf.ByteString
        getInfoBytes() {
      java.lang.Object ref = info_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        info_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 17;
    private int timestamp_;
    /**
     * <code>int32 timestamp = 17;</code>
     */
    public int getTimestamp() {
      return timestamp_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIpPorto2NameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ipPorto2Name_);
      }
      if (!getSrcIpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, srcIp_);
      }
      if (srcPort_ != 0) {
        output.writeUInt32(3, srcPort_);
      }
      if (!getDstIpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, dstIp_);
      }
      if (dstPort_ != 0) {
        output.writeUInt32(5, dstPort_);
      }
      if (!getProtoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, proto_);
      }
      if (srcPktNums_ != 0) {
        output.writeUInt32(7, srcPktNums_);
      }
      if (srcBytes_ != 0) {
        output.writeUInt32(8, srcBytes_);
      }
      if (dstPktNums_ != 0) {
        output.writeUInt32(9, dstPktNums_);
      }
      if (dstBytes_ != 0) {
        output.writeUInt32(10, dstBytes_);
      }
      if (vlan_ != 0) {
        output.writeUInt32(11, vlan_);
      }
      if (!getHostBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, host_);
      }
      if (!getClientBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 13, client_);
      }
      if (!getServerBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 14, server_);
      }
      if (!getBtHashBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 15, btHash_);
      }
      if (!getInfoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 16, info_);
      }
      if (timestamp_ != 0) {
        output.writeInt32(17, timestamp_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIpPorto2NameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, ipPorto2Name_);
      }
      if (!getSrcIpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, srcIp_);
      }
      if (srcPort_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, srcPort_);
      }
      if (!getDstIpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, dstIp_);
      }
      if (dstPort_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, dstPort_);
      }
      if (!getProtoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, proto_);
      }
      if (srcPktNums_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, srcPktNums_);
      }
      if (srcBytes_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(8, srcBytes_);
      }
      if (dstPktNums_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(9, dstPktNums_);
      }
      if (dstBytes_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(10, dstBytes_);
      }
      if (vlan_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(11, vlan_);
      }
      if (!getHostBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, host_);
      }
      if (!getClientBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, client_);
      }
      if (!getServerBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, server_);
      }
      if (!getBtHashBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, btHash_);
      }
      if (!getInfoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(16, info_);
      }
      if (timestamp_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(17, timestamp_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof mydpi.Packet.packet)) {
        return super.equals(obj);
      }
      mydpi.Packet.packet other = (mydpi.Packet.packet) obj;

      boolean result = true;
      result = result && getIpPorto2Name()
          .equals(other.getIpPorto2Name());
      result = result && getSrcIp()
          .equals(other.getSrcIp());
      result = result && (getSrcPort()
          == other.getSrcPort());
      result = result && getDstIp()
          .equals(other.getDstIp());
      result = result && (getDstPort()
          == other.getDstPort());
      result = result && getProto()
          .equals(other.getProto());
      result = result && (getSrcPktNums()
          == other.getSrcPktNums());
      result = result && (getSrcBytes()
          == other.getSrcBytes());
      result = result && (getDstPktNums()
          == other.getDstPktNums());
      result = result && (getDstBytes()
          == other.getDstBytes());
      result = result && (getVlan()
          == other.getVlan());
      result = result && getHost()
          .equals(other.getHost());
      result = result && getClient()
          .equals(other.getClient());
      result = result && getServer()
          .equals(other.getServer());
      result = result && getBtHash()
          .equals(other.getBtHash());
      result = result && getInfo()
          .equals(other.getInfo());
      result = result && (getTimestamp()
          == other.getTimestamp());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IPPORTO2NAME_FIELD_NUMBER;
      hash = (53 * hash) + getIpPorto2Name().hashCode();
      hash = (37 * hash) + SRCIP_FIELD_NUMBER;
      hash = (53 * hash) + getSrcIp().hashCode();
      hash = (37 * hash) + SRCPORT_FIELD_NUMBER;
      hash = (53 * hash) + getSrcPort();
      hash = (37 * hash) + DSTIP_FIELD_NUMBER;
      hash = (53 * hash) + getDstIp().hashCode();
      hash = (37 * hash) + DSTPORT_FIELD_NUMBER;
      hash = (53 * hash) + getDstPort();
      hash = (37 * hash) + PROTO_FIELD_NUMBER;
      hash = (53 * hash) + getProto().hashCode();
      hash = (37 * hash) + SRCPKTNUMS_FIELD_NUMBER;
      hash = (53 * hash) + getSrcPktNums();
      hash = (37 * hash) + SRCBYTES_FIELD_NUMBER;
      hash = (53 * hash) + getSrcBytes();
      hash = (37 * hash) + DSTPKTNUMS_FIELD_NUMBER;
      hash = (53 * hash) + getDstPktNums();
      hash = (37 * hash) + DSTBYTES_FIELD_NUMBER;
      hash = (53 * hash) + getDstBytes();
      hash = (37 * hash) + VLAN_FIELD_NUMBER;
      hash = (53 * hash) + getVlan();
      hash = (37 * hash) + HOST_FIELD_NUMBER;
      hash = (53 * hash) + getHost().hashCode();
      hash = (37 * hash) + CLIENT_FIELD_NUMBER;
      hash = (53 * hash) + getClient().hashCode();
      hash = (37 * hash) + SERVER_FIELD_NUMBER;
      hash = (53 * hash) + getServer().hashCode();
      hash = (37 * hash) + BTHASH_FIELD_NUMBER;
      hash = (53 * hash) + getBtHash().hashCode();
      hash = (37 * hash) + INFO_FIELD_NUMBER;
      hash = (53 * hash) + getInfo().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimestamp();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static mydpi.Packet.packet parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mydpi.Packet.packet parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mydpi.Packet.packet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mydpi.Packet.packet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mydpi.Packet.packet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mydpi.Packet.packet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mydpi.Packet.packet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mydpi.Packet.packet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static mydpi.Packet.packet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static mydpi.Packet.packet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static mydpi.Packet.packet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mydpi.Packet.packet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(mydpi.Packet.packet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mydpi.packet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mydpi.packet)
        mydpi.Packet.packetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mydpi.Packet.internal_static_mydpi_packet_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mydpi.Packet.internal_static_mydpi_packet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mydpi.Packet.packet.class, mydpi.Packet.packet.Builder.class);
      }

      // Construct using mydpi.Packet.packet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        ipPorto2Name_ = "";

        srcIp_ = "";

        srcPort_ = 0;

        dstIp_ = "";

        dstPort_ = 0;

        proto_ = "";

        srcPktNums_ = 0;

        srcBytes_ = 0;

        dstPktNums_ = 0;

        dstBytes_ = 0;

        vlan_ = 0;

        host_ = "";

        client_ = "";

        server_ = "";

        btHash_ = "";

        info_ = "";

        timestamp_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mydpi.Packet.internal_static_mydpi_packet_descriptor;
      }

      @java.lang.Override
      public mydpi.Packet.packet getDefaultInstanceForType() {
        return mydpi.Packet.packet.getDefaultInstance();
      }

      @java.lang.Override
      public mydpi.Packet.packet build() {
        mydpi.Packet.packet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public mydpi.Packet.packet buildPartial() {
        mydpi.Packet.packet result = new mydpi.Packet.packet(this);
        result.ipPorto2Name_ = ipPorto2Name_;
        result.srcIp_ = srcIp_;
        result.srcPort_ = srcPort_;
        result.dstIp_ = dstIp_;
        result.dstPort_ = dstPort_;
        result.proto_ = proto_;
        result.srcPktNums_ = srcPktNums_;
        result.srcBytes_ = srcBytes_;
        result.dstPktNums_ = dstPktNums_;
        result.dstBytes_ = dstBytes_;
        result.vlan_ = vlan_;
        result.host_ = host_;
        result.client_ = client_;
        result.server_ = server_;
        result.btHash_ = btHash_;
        result.info_ = info_;
        result.timestamp_ = timestamp_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mydpi.Packet.packet) {
          return mergeFrom((mydpi.Packet.packet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mydpi.Packet.packet other) {
        if (other == mydpi.Packet.packet.getDefaultInstance()) return this;
        if (!other.getIpPorto2Name().isEmpty()) {
          ipPorto2Name_ = other.ipPorto2Name_;
          onChanged();
        }
        if (!other.getSrcIp().isEmpty()) {
          srcIp_ = other.srcIp_;
          onChanged();
        }
        if (other.getSrcPort() != 0) {
          setSrcPort(other.getSrcPort());
        }
        if (!other.getDstIp().isEmpty()) {
          dstIp_ = other.dstIp_;
          onChanged();
        }
        if (other.getDstPort() != 0) {
          setDstPort(other.getDstPort());
        }
        if (!other.getProto().isEmpty()) {
          proto_ = other.proto_;
          onChanged();
        }
        if (other.getSrcPktNums() != 0) {
          setSrcPktNums(other.getSrcPktNums());
        }
        if (other.getSrcBytes() != 0) {
          setSrcBytes(other.getSrcBytes());
        }
        if (other.getDstPktNums() != 0) {
          setDstPktNums(other.getDstPktNums());
        }
        if (other.getDstBytes() != 0) {
          setDstBytes(other.getDstBytes());
        }
        if (other.getVlan() != 0) {
          setVlan(other.getVlan());
        }
        if (!other.getHost().isEmpty()) {
          host_ = other.host_;
          onChanged();
        }
        if (!other.getClient().isEmpty()) {
          client_ = other.client_;
          onChanged();
        }
        if (!other.getServer().isEmpty()) {
          server_ = other.server_;
          onChanged();
        }
        if (!other.getBtHash().isEmpty()) {
          btHash_ = other.btHash_;
          onChanged();
        }
        if (!other.getInfo().isEmpty()) {
          info_ = other.info_;
          onChanged();
        }
        if (other.getTimestamp() != 0) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        mydpi.Packet.packet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (mydpi.Packet.packet) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object ipPorto2Name_ = "";
      /**
       * <code>string ipPorto2Name = 1;</code>
       */
      public java.lang.String getIpPorto2Name() {
        java.lang.Object ref = ipPorto2Name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ipPorto2Name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ipPorto2Name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIpPorto2NameBytes() {
        java.lang.Object ref = ipPorto2Name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ipPorto2Name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ipPorto2Name = 1;</code>
       */
      public Builder setIpPorto2Name(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ipPorto2Name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ipPorto2Name = 1;</code>
       */
      public Builder clearIpPorto2Name() {
        
        ipPorto2Name_ = getDefaultInstance().getIpPorto2Name();
        onChanged();
        return this;
      }
      /**
       * <code>string ipPorto2Name = 1;</code>
       */
      public Builder setIpPorto2NameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ipPorto2Name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object srcIp_ = "";
      /**
       * <code>string srcIp = 2;</code>
       */
      public java.lang.String getSrcIp() {
        java.lang.Object ref = srcIp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          srcIp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string srcIp = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSrcIpBytes() {
        java.lang.Object ref = srcIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          srcIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string srcIp = 2;</code>
       */
      public Builder setSrcIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        srcIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string srcIp = 2;</code>
       */
      public Builder clearSrcIp() {
        
        srcIp_ = getDefaultInstance().getSrcIp();
        onChanged();
        return this;
      }
      /**
       * <code>string srcIp = 2;</code>
       */
      public Builder setSrcIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        srcIp_ = value;
        onChanged();
        return this;
      }

      private int srcPort_ ;
      /**
       * <code>uint32 srcPort = 3;</code>
       */
      public int getSrcPort() {
        return srcPort_;
      }
      /**
       * <code>uint32 srcPort = 3;</code>
       */
      public Builder setSrcPort(int value) {
        
        srcPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 srcPort = 3;</code>
       */
      public Builder clearSrcPort() {
        
        srcPort_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object dstIp_ = "";
      /**
       * <code>string dstIp = 4;</code>
       */
      public java.lang.String getDstIp() {
        java.lang.Object ref = dstIp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dstIp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string dstIp = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDstIpBytes() {
        java.lang.Object ref = dstIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dstIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string dstIp = 4;</code>
       */
      public Builder setDstIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dstIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string dstIp = 4;</code>
       */
      public Builder clearDstIp() {
        
        dstIp_ = getDefaultInstance().getDstIp();
        onChanged();
        return this;
      }
      /**
       * <code>string dstIp = 4;</code>
       */
      public Builder setDstIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dstIp_ = value;
        onChanged();
        return this;
      }

      private int dstPort_ ;
      /**
       * <code>uint32 dstPort = 5;</code>
       */
      public int getDstPort() {
        return dstPort_;
      }
      /**
       * <code>uint32 dstPort = 5;</code>
       */
      public Builder setDstPort(int value) {
        
        dstPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 dstPort = 5;</code>
       */
      public Builder clearDstPort() {
        
        dstPort_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object proto_ = "";
      /**
       * <code>string proto = 6;</code>
       */
      public java.lang.String getProto() {
        java.lang.Object ref = proto_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          proto_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string proto = 6;</code>
       */
      public com.google.protobuf.ByteString
          getProtoBytes() {
        java.lang.Object ref = proto_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          proto_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string proto = 6;</code>
       */
      public Builder setProto(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        proto_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string proto = 6;</code>
       */
      public Builder clearProto() {
        
        proto_ = getDefaultInstance().getProto();
        onChanged();
        return this;
      }
      /**
       * <code>string proto = 6;</code>
       */
      public Builder setProtoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        proto_ = value;
        onChanged();
        return this;
      }

      private int srcPktNums_ ;
      /**
       * <code>uint32 srcPktNums = 7;</code>
       */
      public int getSrcPktNums() {
        return srcPktNums_;
      }
      /**
       * <code>uint32 srcPktNums = 7;</code>
       */
      public Builder setSrcPktNums(int value) {
        
        srcPktNums_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 srcPktNums = 7;</code>
       */
      public Builder clearSrcPktNums() {
        
        srcPktNums_ = 0;
        onChanged();
        return this;
      }

      private int srcBytes_ ;
      /**
       * <code>uint32 srcBytes = 8;</code>
       */
      public int getSrcBytes() {
        return srcBytes_;
      }
      /**
       * <code>uint32 srcBytes = 8;</code>
       */
      public Builder setSrcBytes(int value) {
        
        srcBytes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 srcBytes = 8;</code>
       */
      public Builder clearSrcBytes() {
        
        srcBytes_ = 0;
        onChanged();
        return this;
      }

      private int dstPktNums_ ;
      /**
       * <code>uint32 dstPktNums = 9;</code>
       */
      public int getDstPktNums() {
        return dstPktNums_;
      }
      /**
       * <code>uint32 dstPktNums = 9;</code>
       */
      public Builder setDstPktNums(int value) {
        
        dstPktNums_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 dstPktNums = 9;</code>
       */
      public Builder clearDstPktNums() {
        
        dstPktNums_ = 0;
        onChanged();
        return this;
      }

      private int dstBytes_ ;
      /**
       * <code>uint32 dstBytes = 10;</code>
       */
      public int getDstBytes() {
        return dstBytes_;
      }
      /**
       * <code>uint32 dstBytes = 10;</code>
       */
      public Builder setDstBytes(int value) {
        
        dstBytes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 dstBytes = 10;</code>
       */
      public Builder clearDstBytes() {
        
        dstBytes_ = 0;
        onChanged();
        return this;
      }

      private int vlan_ ;
      /**
       * <code>uint32 vlan = 11;</code>
       */
      public int getVlan() {
        return vlan_;
      }
      /**
       * <code>uint32 vlan = 11;</code>
       */
      public Builder setVlan(int value) {
        
        vlan_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 vlan = 11;</code>
       */
      public Builder clearVlan() {
        
        vlan_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object host_ = "";
      /**
       * <code>string host = 12;</code>
       */
      public java.lang.String getHost() {
        java.lang.Object ref = host_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          host_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string host = 12;</code>
       */
      public com.google.protobuf.ByteString
          getHostBytes() {
        java.lang.Object ref = host_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          host_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string host = 12;</code>
       */
      public Builder setHost(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        host_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string host = 12;</code>
       */
      public Builder clearHost() {
        
        host_ = getDefaultInstance().getHost();
        onChanged();
        return this;
      }
      /**
       * <code>string host = 12;</code>
       */
      public Builder setHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        host_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object client_ = "";
      /**
       * <code>string client = 13;</code>
       */
      public java.lang.String getClient() {
        java.lang.Object ref = client_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          client_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string client = 13;</code>
       */
      public com.google.protobuf.ByteString
          getClientBytes() {
        java.lang.Object ref = client_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          client_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string client = 13;</code>
       */
      public Builder setClient(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        client_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string client = 13;</code>
       */
      public Builder clearClient() {
        
        client_ = getDefaultInstance().getClient();
        onChanged();
        return this;
      }
      /**
       * <code>string client = 13;</code>
       */
      public Builder setClientBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        client_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object server_ = "";
      /**
       * <code>string server = 14;</code>
       */
      public java.lang.String getServer() {
        java.lang.Object ref = server_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          server_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string server = 14;</code>
       */
      public com.google.protobuf.ByteString
          getServerBytes() {
        java.lang.Object ref = server_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          server_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string server = 14;</code>
       */
      public Builder setServer(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        server_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string server = 14;</code>
       */
      public Builder clearServer() {
        
        server_ = getDefaultInstance().getServer();
        onChanged();
        return this;
      }
      /**
       * <code>string server = 14;</code>
       */
      public Builder setServerBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        server_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object btHash_ = "";
      /**
       * <code>string btHash = 15;</code>
       */
      public java.lang.String getBtHash() {
        java.lang.Object ref = btHash_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          btHash_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string btHash = 15;</code>
       */
      public com.google.protobuf.ByteString
          getBtHashBytes() {
        java.lang.Object ref = btHash_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          btHash_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string btHash = 15;</code>
       */
      public Builder setBtHash(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        btHash_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string btHash = 15;</code>
       */
      public Builder clearBtHash() {
        
        btHash_ = getDefaultInstance().getBtHash();
        onChanged();
        return this;
      }
      /**
       * <code>string btHash = 15;</code>
       */
      public Builder setBtHashBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        btHash_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object info_ = "";
      /**
       * <code>string info = 16;</code>
       */
      public java.lang.String getInfo() {
        java.lang.Object ref = info_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          info_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string info = 16;</code>
       */
      public com.google.protobuf.ByteString
          getInfoBytes() {
        java.lang.Object ref = info_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          info_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string info = 16;</code>
       */
      public Builder setInfo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        info_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string info = 16;</code>
       */
      public Builder clearInfo() {
        
        info_ = getDefaultInstance().getInfo();
        onChanged();
        return this;
      }
      /**
       * <code>string info = 16;</code>
       */
      public Builder setInfoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        info_ = value;
        onChanged();
        return this;
      }

      private int timestamp_ ;
      /**
       * <code>int32 timestamp = 17;</code>
       */
      public int getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>int32 timestamp = 17;</code>
       */
      public Builder setTimestamp(int value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 timestamp = 17;</code>
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:mydpi.packet)
    }

    // @@protoc_insertion_point(class_scope:mydpi.packet)
    private static final mydpi.Packet.packet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new mydpi.Packet.packet();
    }

    public static mydpi.Packet.packet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<packet>
        PARSER = new com.google.protobuf.AbstractParser<packet>() {
      @java.lang.Override
      public packet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new packet(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<packet> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<packet> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public mydpi.Packet.packet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mydpi_packet_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mydpi_packet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014packet.proto\022\005mydpi\"\246\002\n\006packet\022\024\n\014ipPo" +
      "rto2Name\030\001 \001(\t\022\r\n\005srcIp\030\002 \001(\t\022\017\n\007srcPort" +
      "\030\003 \001(\r\022\r\n\005dstIp\030\004 \001(\t\022\017\n\007dstPort\030\005 \001(\r\022\r" +
      "\n\005proto\030\006 \001(\t\022\022\n\nsrcPktNums\030\007 \001(\r\022\020\n\010src" +
      "Bytes\030\010 \001(\r\022\022\n\ndstPktNums\030\t \001(\r\022\020\n\010dstBy" +
      "tes\030\n \001(\r\022\014\n\004vlan\030\013 \001(\r\022\014\n\004host\030\014 \001(\t\022\016\n" +
      "\006client\030\r \001(\t\022\016\n\006server\030\016 \001(\t\022\016\n\006btHash\030" +
      "\017 \001(\t\022\014\n\004info\030\020 \001(\t\022\021\n\ttimestamp\030\021 \001(\005b\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_mydpi_packet_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mydpi_packet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mydpi_packet_descriptor,
        new java.lang.String[] { "IpPorto2Name", "SrcIp", "SrcPort", "DstIp", "DstPort", "Proto", "SrcPktNums", "SrcBytes", "DstPktNums", "DstBytes", "Vlan", "Host", "Client", "Server", "BtHash", "Info", "Timestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
